export const PAYMENT_PUBLIC_SIGNALS = [
  "action",
  "contextDigest",
  "membershipRoot",
  "nullifierCount",
  "nullifier0",
  "nullifier1",
  "nullifier2",
  "nullifier3",
  "outputCount",
  "outputCommitment0",
  "outputCommitment1",
  "outputCommitment2",
  "outputCommitment3",
  "outputEnvelopeHash0",
  "outputEnvelopeHash1",
  "outputEnvelopeHash2",
  "outputEnvelopeHash3",
  "attachmentHash",
  "publicAmountSign",
  "publicAmountMagnitude",
];

export const PAYMENT_CIRCUITS = [
  { name: "deposit", code: 0, action: 0, inputCount: 0, outputCount: 2 },
  { name: "transfer_one", code: 1, action: 1, inputCount: 1, outputCount: 4 },
  { name: "transfer_two", code: 2, action: 1, inputCount: 2, outputCount: 4 },
  { name: "transfer_four", code: 3, action: 1, inputCount: 4, outputCount: 4 },
  { name: "withdraw_one", code: 4, action: 2, inputCount: 1, outputCount: 3 },
  { name: "withdraw_two", code: 5, action: 2, inputCount: 2, outputCount: 3 },
  { name: "withdraw_four", code: 6, action: 2, inputCount: 4, outputCount: 3 },
];

export const PAYMENT_CONTEXT_FIELDS = [
  "version",
  "action",
  "noteSchema",
  "networkHigh",
  "networkLow",
  "vaultHigh",
  "vaultLow",
  "tokenHigh",
  "tokenLow",
  "verifierHigh",
  "verifierLow",
  "actionIdHigh",
  "actionIdLow",
  "expiry",
  "publicAccountHigh",
  "publicAccountLow",
  "publicAmountSign",
  "publicAmountMagnitude",
  "outputCount",
  "appendCount",
  "emergency",
  "feeEpoch",
  "relayFeeAmount",
  "protocolFeeAmount",
  "relaySpendPublicKey",
  "relayViewingPublicKeyX",
  "relayViewingPublicKeyY",
  "protocolSpendPublicKey",
  "protocolViewingPublicKeyX",
  "protocolViewingPublicKeyY",
  "attachmentHash",
  "relayQuoteDigest",
];
